# Generated by Django 3.2.7 on 2021-10-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='examen',
        ),
        migrations.AddField(
            model_name='portada',
            name='examen',
            field=models.ManyToManyField(to='core.Examen'),
        ),
    ]
