# Generated by Django 3.2.7 on 2021-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['order', 'title'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='universidad',
        ),
        migrations.AddField(
            model_name='page',
            name='universidad',
            field=models.ManyToManyField(to='pages.Categoria'),
        ),
    ]
