# Generated by Django 3.2.7 on 2021-10-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211018_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='universidad',
            new_name='categoria',
        ),
    ]
