# Generated by Django 3.2.7 on 2021-10-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_universidad_page_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'universidad', 'verbose_name_plural': 'universidades'},
        ),
    ]
